Update patch set 6
Patch Set 6: Code-Review-1

S3Repository needs org.eclipse.jgit.http.apache artefact which is missing in buck dependencies so I am experiencing

java.lang.NoClassDefFoundError: org/eclipse/jgit/transport/http/apache/HttpClientConnectionFactory

Patch-set: 6
Label: Code-Review=-1